version: '3'
services:
  haproxy:
    image: haproxy:2.0.2
    volumes:
      - ./resources/haproxy:/usr/local/etc/haproxy:ro
    ports:
      - "9080:80"

  nginx-backend:
    image: nginx
    volumes:
      - ./resources/backend:/usr/share/nginx/html

  error-backend:
    image: nginx
    volumes:
      - ./resources/errors:/usr/share/nginx/html

  auth-backend:
    build: .
    volumes:
      - .:/app
    working_dir: /app

  openldap:
    image: clems4ever/openldap
    environment:
      - SLAPD_ORGANISATION=MyCompany
      - SLAPD_DOMAIN=example.com
      - SLAPD_PASSWORD=password
      - SLAPD_CONFIG_PASSWORD=password
      - SLAPD_ADDITIONAL_MODULES=memberof
      - SLAPD_ADDITIONAL_SCHEMAS=openldap
      - SLAPD_FORCE_RECONFIGURE=true
    volumes:
      - ./resources/ldap/base.ldif:/etc/ldap.dist/prepopulate/base.ldif
      - ./resources/ldap/access.rules:/etc/ldap.dist/prepopulate/access.rules